/**
 * schedule command — generate a CI/cron schedule for running HTTP Forge suites.
 *
 *   http-forge schedule --suite smoke-tests --env staging --cron "0 * /6 * * *"
 *   http-forge schedule --suite smoke-tests --print-cron
 *
 * Generates a GitHub Actions workflow YAML, a shell cron entry, or both.
 * Does not require a running workspace — purely a file generator.
 */

import * as fs from 'fs';
import * as path from 'path';

export async function handleSchedule(args: string[]): Promise<void> {
  if (args[0] === '--help' || args[0] === '-h') {
    printUsage();
    return;
  }

  let suite: string | undefined;
  let environment: string | undefined;
  let cron = '0 */6 * * *'; // default: every 6 hours
  let workspace = process.env.HTTP_FORGE_WORKSPACE ?? '.';
  let output: string | undefined;
  let printCron = false;
  let reporter = 'junit';
  let reporterPath = 'test-results/api-results.xml';
  let exitCode = true;
  let format: string = 'github-actions';

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if ((arg === '--suite' || arg === '-s') && i + 1 < args.length) {
      suite = args[++i];
    } else if ((arg === '--env' || arg === '--environment') && i + 1 < args.length) {
      environment = args[++i];
    } else if (arg === '--cron' && i + 1 < args.length) {
      cron = args[++i];
    } else if (arg === '--workspace' && i + 1 < args.length) {
      workspace = args[++i];
    } else if ((arg === '--output' || arg === '-o') && i + 1 < args.length) {
      output = args[++i];
    } else if (arg === '--reporter' && i + 1 < args.length) {
      const spec = args[++i];
      const colonIdx = spec.indexOf(':');
      if (colonIdx !== -1) {
        reporter = spec.slice(0, colonIdx);
        reporterPath = spec.slice(colonIdx + 1);
      } else {
        reporter = spec;
      }
    } else if (arg === '--no-exit-code') {
      exitCode = false;
    } else if (arg === '--print-cron') {
      printCron = true;
      format = 'cron';
    } else if (arg === '--format' && i + 1 < args.length) {
      const f = args[++i];
      if (f === 'github-actions' || f === 'cron' || f === 'both') format = f;
    }
  }

  if (!suite) {
    console.error('Error: --suite is required');
    printUsage();
    process.exit(2);
  }

  if (printCron || format === 'cron' || format === 'both') {
    const cronCmd = buildCronEntry(suite, environment, workspace, reporter, reporterPath, exitCode);
    console.log('\n# Cron entry (add to crontab -e):');
    console.log(cronCmd);
  }

  if (format === 'github-actions' || format === 'both') {
    const yaml = buildGitHubActionsWorkflow(suite, environment, workspace, cron, reporter, reporterPath, exitCode);
    const outPath = output ?? `.github/workflows/http-forge-${slugify(suite)}.yml`;
    const dir = path.dirname(outPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outPath, yaml, 'utf8');
    console.log(`\nGitHub Actions workflow written to: ${outPath}`);
    console.log(`\nNext steps:`);
    console.log(`  1. Commit ${outPath} to your repository`);
    console.log(`  2. Set any required secrets in GitHub → Settings → Secrets and variables → Actions`);
    console.log(`  3. The workflow runs on push and on the schedule: ${cron} (UTC)`);
  }
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function buildCronEntry(
  suite: string,
  environment: string | undefined,
  workspace: string,
  reporter: string,
  reporterPath: string,
  exitCode: boolean
): string {
  const parts = [
    'http-forge run-suite',
    `--workspace "${workspace}"`,
    `--suite "${suite}"`,
    environment ? `--environment "${environment}"` : '',
    `--reporter ${reporter}:${reporterPath}`,
    exitCode ? '--exit-code' : '',
  ].filter(Boolean);
  return `# HTTP Forge — ${suite}\n0 */6 * * *  cd /path/to/workspace && ${parts.join(' ')} >> /var/log/http-forge.log 2>&1`;
}

function buildGitHubActionsWorkflow(
  suite: string,
  environment: string | undefined,
  workspace: string,
  cron: string,
  reporter: string,
  reporterPath: string,
  exitCode: boolean
): string {
  const suiteSlug = slugify(suite);
  const artifactName = `http-forge-${suiteSlug}-results`;
  const envLine = environment ? `\n          HTTP_FORGE_ENV: ${environment}` : '';
  const envArg = environment ? `\n              --environment ${environment} \\` : '';
  const exitCodeArg = exitCode ? '\n              --exit-code \\' : '';

  return `# Generated by http-forge schedule — edit as needed
name: HTTP Forge — ${suite}

on:
  push:
    branches: [main, master]
  schedule:
    # ${cron} UTC — https://crontab.guru/#${cron.replace(/ /g, '_')}
    - cron: '${cron}'
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API suite \\'${suite}\\'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HTTP Forge CLI
        run: npm install -g @http-forge/cli

      - name: Run API suite
        run: |
          http-forge run-suite \\
              --workspace ${workspace} \\
              --suite "${suite}" \\${envArg}
              --reporter ${reporter}:${reporterPath} \\${exitCodeArg}
              --output json
        env:
          # Add secrets your collection needs, e.g.:
          # API_KEY: \${{ secrets.API_KEY }}
          HTTP_FORGE_WORKSPACE: ${workspace}${envLine}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${artifactName}
          path: ${reporterPath}
          retention-days: 30
${reporter === 'junit' ? `
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${reporterPath}
` : ''}`;
}

function printUsage(): void {
  console.log(`
Usage: http-forge schedule [options]

Generate a CI/cron schedule configuration for running an HTTP Forge suite.

Required:
  --suite <name>             Test suite name (or id/slug)

Options:
  --env <name>               Environment to pass to the suite run
  --cron <expr>              Cron expression for scheduled runs (default: "0 */6 * * *")
  --output <path>            Output file path (default: .github/workflows/http-forge-<suite>.yml)
  --reporter <spec>          Reporter to use, e.g. "junit:results/junit.xml" (default: junit)
  --no-exit-code             Do not fail the job on test assertion failures
  --format <type>            Output format: github-actions | cron | both (default: github-actions)
  --print-cron               Print a cron entry to stdout (alias for --format cron)
  --workspace <path>         Workspace folder (default: \$HTTP_FORGE_WORKSPACE or cwd)

Examples:
  # Generate a GitHub Actions workflow
  http-forge schedule --suite smoke-tests --env staging --cron "0 */6 * * *"

  # Generate both GitHub Actions workflow and cron entry
  http-forge schedule --suite regression --env prod --format both

  # Just print a cron entry
  http-forge schedule --suite smoke-tests --print-cron

  # Custom output path and JUnit reporter
  http-forge schedule --suite e2e --output .github/workflows/e2e-monitor.yml \\
    --reporter "junit:test-results/e2e.xml"
`);
}
